CREATE TABLE IF NOT EXISTS `martyr_graves` (
                                               `id` bigint(20) NOT NULL AUTO_INCREMENT,
                                               `created_at` datetime(6) DEFAULT NULL,
                                               `updated_at` datetime(6) DEFAULT NULL,
                                               `additional_field1` varchar(255) DEFAULT NULL,
                                               `additional_field2` varchar(255) DEFAULT NULL,
                                               `additional_field3` varchar(255) DEFAULT NULL,
                                               `additional_field4` varchar(255) DEFAULT NULL,
                                               `code_name` varchar(255) DEFAULT NULL,
                                               `commune` varchar(255) DEFAULT NULL,
                                               `date_of_death` varchar(255) DEFAULT NULL,
                                               `date_of_enlistment` varchar(255) DEFAULT NULL,
                                               `dieu_chinh` varchar(255) DEFAULT NULL,
                                               `district` varchar(255) DEFAULT NULL,
                                               `full_name` varchar(255) DEFAULT NULL,
                                               `home_town` varchar(255) DEFAULT NULL,
                                               `image` varchar(255) DEFAULT NULL,
                                               `name` varchar(255) DEFAULT NULL,
                                               `ngay_thang_nam` varchar(255) DEFAULT NULL,
                                               `note` varchar(255) DEFAULT NULL,
                                               `place_of_exhumation` varchar(255) DEFAULT NULL,
                                               `quy_tap` varchar(255) DEFAULT NULL,
                                               `rank_position_unit` varchar(255) DEFAULT NULL,
                                               `year_of_birth` varchar(255) DEFAULT NULL,
                                               `deleted` bit(1) NOT NULL COMMENT 'Soft-delete indicator',
                                               `grave_row_id` bigint(20) DEFAULT NULL,
                                               PRIMARY KEY (`id`),
                                               KEY `FKfqqvd8jjsxvqiga0fu0hpq3h` (`grave_row_id`),
                                               CONSTRAINT `FKfqqvd8jjsxvqiga0fu0hpq3h` FOREIGN KEY (`grave_row_id`) REFERENCES `grave_rows` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3017 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;