version: '3.1'

services:
  postgis:
    image: postgis/postgis:15-3.3
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: lietsi
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - weblietsi-postgres:/var/lib/postgresql/data

volumes:
    weblietsi-postgres:
      external: true