version: '3.1'
services:
  maven:
    image: maven:3.8.3-openjdk-17-slim
    container_name: lietsi-maven
    volumes:
      - maven-repo:/root/.m2
      - .:/app
    working_dir: /app
    command: bash -c "mvn clean install -DskipTests && mvn spring-boot:run"
    networks:
      - lietsi-postgres-net
    depends_on:
      - postgis
    ports:
      - '8000:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgis:5432/lietsi
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_SERVER_PORT: '8080'

  postgis:
    image: postgis/postgis:15-3.3
    restart: always
    ports:
      - '5432:5432'
    networks:
      - lietsi-postgres-net
    environment:
      POSTGRES_DB: lietsi
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - weblietsi-postgres:/var/lib/postgresql/data

networks:
  lietsi-postgres-net:

volumes:
  weblietsi-postgres:
    external: true
  maven-repo:
    external: true