version: '3.1'
services:
  app:
    build: .
    container_name: lietsi-backend
    restart: always
    ports:
      - "8080:8080"   # HTTP port
      - "8443:8443"   # HTTPS port
    networks:
      - lietsi-postgres-net
    depends_on:
      - postgis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgis:5432/lietsi
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_SERVER_PORT: '8080'
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      SSL_KEYSTORE: /app/ssl/keystore.p12
      SSL_PASSWORD: ${SSL_PASSWORD}
      SSL_ALIAS: ${SSL_ALIAS}
      SERVER_SSL_KEY_STORE: ${SSL_KEYSTORE}
      SERVER_SSL_KEY_STORE_PASSWORD: ${SSL_PASSWORD}
      SERVER_SSL_KEY_ALIAS: ${SSL_ALIAS}
      SERVER_HTTP_PORT: '8080'
      SERVER_PORT: '8443'
    volumes:
      - ./ssl:/app/ssl

  postgis:
    image: postgis/postgis:15-3.3
    restart: always
    networks:
      - lietsi-postgres-net
    environment:
      POSTGRES_DB: lietsi
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: postgres
    volumes:
      - weblietsi-postgres:/var/lib/postgresql/data

  backup:
    image: prodrigestivill/postgres-backup-local
    restart: always
    networks:
      - lietsi-postgres-net
    volumes:
      - ./backups:/backups
    environment:
      POSTGRES_HOST: postgis
      POSTGRES_DB: lietsi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      SCHEDULE: '@daily'
      BACKUP_KEEP_DAYS: 7
      BACKUP_KEEP_WEEKS: 4
      BACKUP_KEEP_MONTHS: 6
      HEALTHCHECK_PORT: 8080
    depends_on:
      - postgis

networks:
  lietsi-postgres-net:

volumes:
  weblietsi-postgres:
    external: true
