version: '3.1'

services:
  mariadb:
    image: mariadb:10.6
    restart: always
    ports:
      - '3305:3306'
    expose:
      - '3305'
    environment:
      MYSQL_DATABASE: lietsi
      MARIADB_ROOT_PASSWORD: root
      MYSQL_USER: dev
      MYSQL_PASSWORD: root
    volumes:
      - weblietsi-mariadb:/var/lib/mysql

volumes:
    weblietsi-mariadb:
      external: true