version: '3.1'
services:
  maven:
    image: maven:3.8.3-openjdk-17-slim
    container_name: lietsi-maven
    volumes:
      - maven-repo:/root/.m2
      - .:/app
    working_dir: /app
    command: bash -c "mvn clean install -DskipTests && mvn spring-boot:run"
    networks:
      - lietsi-mariadb-net
    depends_on:
      - mariadb
    ports:
      - '8000:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/lietsi
      SPRING_DATASOURCE_USERNAME: dev
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_SERVER_PORT: '8080'
  mariadb:
    image: mariadb:10.6
    restart: always
    ports:
      - '3305:3306'
    expose:
      - '3305'
    networks:
      - lietsi-mariadb-net
    environment:
      MYSQL_DATABASE: lietsi
      MARIADB_ROOT_PASSWORD: root
      MYSQL_USER: dev
      MYSQL_PASSWORD: root
    volumes:
      - weblietsi-mariadb:/var/lib/mysql

networks:
  lietsi-mariadb-net:

volumes:
  weblietsi-mariadb:
    external: true
  maven-repo:
    external: true