spring:
  application:
    name: weblietsi-backend
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
  datasource:
    url: jdbc:postgresql://localhost:5432/lietsi
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    validateOnMigrate: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}
    baselineOnMigrate: true
    baselineVersion: 0
    locations: classpath:db/migration
    postgresql:
      transactional.lock: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
          nodeValue: TRACE
        SQL: DEBUG
    root: INFO

server:
  port: 8080

application:
  jwt:
    accessToken:
      expiration: 86400
    refreshToken:
      expiration: 2592000

# springdoc:
#   swagger-ui:
#     operations-sorter: method
#     path: /

postgis:
  force-axis-order: true