spring:
  application:
    name: weblietsi-backend
  mail:
    host: smtp.gmail.com
    port: 587
    username: admin@gmail.com
    password: admin
  datasource:
    url: jdbc:mariadb://localhost:3305/lietsi
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MariaDBDialect
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}
    baselineOnMigrate: true
    baselineVersion: 0
    locations: classpath:db/migration


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
          nodeValue: TRACE
        SQL: DEBUG
    root: INFO

server:
  port: 8080

application:
  jwt:
    accessToken:
      expiration: 86400
    refreshToken:
      expiration: 2592000

springdoc:
  swagger-ui:
    operations-sorter: method
    path: /